steps:
  #- popover:
  #    title: "Welcome to the Financial Independence Simulator"
  #    description: "This is a tool to help you plan for your financial future. It allows you to simulate different scenarios to see how different decisions could affect your financial situation."

  - element: "#startingPosition"
    popover:
      description: "<b>This is where you describe your current financial situation.</b><p/>It's the starting point for the simulation."
      side: "right"
      align: "start"
      
  - element: "#StartingAge"
    popover:
      description: "Enter your current age."
      side: "right"
      align: "start"
  
  - element: "#InitialSavings"
    popover:
      description: "<b>Enter your current savings.</b><p/>Any cash you have sitting in your bank accounts or safety box, not earning significant interest."
      side: "right"
      align: "start"
  
  - element: "#InitialPension"
    popover:
      description: "<b>Enter the total amount in your private pension funds.</b><p/>If you haven't contributed to one yet, enter '0'. If you have more than one pension fund, enter the total amount here."
      side: "right"
      align: "start"

  - element: "#InitialETFs"
    popover:
      description: "<b>Enter the current value of your ETF investments.</b><p/>Keep in mind that since I don't know when you bought those ETFs I can't track their deemed disposal tax, so I 'buy' them at the start of the simulation and you will see the corresponding tax being paid 8 years into the run and every 8 years thereafter."
      side: "right"
      align: "start"
  
  - element: "#InitialTrusts"
    popover:
      description: "<b>Enter the current value in your investment trusts or stocks.</b><p/>Keep in mind that since I don't know when you bought those trusts or shares I can't track their deemed disposal tax, so I 'buy' them at the start of the simulation and you will see the corresponding tax being paid 8 years into the run and every 8 years thereafter."
      side: "right"
      align: "start"

  - element: "#targetsAllocations"
    popover:
      description: "<b>Here you describe your financial plan.</b>"
      side: "right"
      align: "start"
  
  - element: "#RetirementAge"
    popover:
      description: "<b>This is the age at which you plan to retire.</b>"
      side: "right"
      align: "start"

  - element: "#TargetAge"
    popover:
      description: "<b>This is your life expectancy.</b><p/>The simulation will end at this age, and will be successful if you reach this age without running out of money."
      side: "right"
      align: "start"

  - element: "#EmergencyStash"
    popover:
      description: "<b>This is the amount of money you plan to have in cash to cover unexpected expenses.</b><p/>This will be inflation adjusted."
      side: "right"
      align: "start"

  - element: "#EtfAllocation"
    popover:
      description: "<b>This is the percentage of your portfolio that you plan to have in ETFs.</b><p/>Any cash remaining after funding your emergency stash will be invested in ETFs in this proportion. The sum of ETFs and Trusts can't exceed 100%. If they add up to less than 100%, you'll be saving the remainder in cash."
      side: "right"
      align: "start"

  - element: "#TrustAllocation"
    popover:
      description: "<b>This is the percentage of your portfolio that you plan to have in investment trusts or shares.</b><p/>Any cash remaining after funding your emergency stash will be invested in trusts or shares in this proportion. The sum of ETFs and Trusts can't exceed 100%. If they add up to less than 100%, you'll be saving the remainder in cash."
      side: "right"
      align: "start"

  - element: "#PensionContributionPercentage"
    popover:
      description: "<b>How much of your age-dependent maximum you want to pay out of your gross salary into a private pension scheme.</b><p/>If you enter 100% here, you will contribute the maximum allowed for your age (15% to 40%). Do not include employer matching contributions here; there's another place for that."
      side: "right"
      align: "start"

  - element: "#PensionContributionCapped"
    popover:
      description: "<b>Whether your pension contribution is capped to match the maximum amount that you can get tax relief on.</b><p/>This limit is the same for everyone, it does not depend on age. If you select 'Yes', your pension contributions will be capped at the maximum allowed. If you select 'No' and your contribution is greater than that limit, you pay income tax on the excess."
      side: "right"
      align: "start"

  - element: "#growthRates"
    popover:
      description: "<b>Here is where you speculate how the economy will do on average in the future.</b><p/>You may want to enter conservative numbers to stress test your scenario. For reference, the average annual growth rate of the S&P500 over its lifetime has been around 10% in US dollars (not adjusted for inflation and not including fees). If you enter volatility numbers larger than zero, I will run a Monte Carlo simulation using these numbers to calculate the probability of success of your scenario."
      side: "right"
      align: "start"

  - element: "#PensionGrowthRate"
    popover:
      description: "<b>This is the expected average annual growth rate of your private pension, not adjusted for inflation.</b><p/>Keep in mind pension funds tend to invest more conservatively and have higher fees, so take that into account when calculating this number."
      side: "right"
      align: "start"

  - element: "#PensionGrowthStdDev"
    popover:
      description: "<b>This is the expected standard deviation of the annual growth rate of your private pension.</b><p/>Keep in mind that pension funds tend to invest more conservatively so may have lower volatility than the stock market. Take that into account when calculating this number."
      side: "right"
      align: "start"

  - element: "#EtfGrowthRate"
    popover:
      description: "<b>This is the expected average annual growth rate of your ETFs, not adjusted for inflation.</b><p/>For reference, the average growth rate of the S&P500 over its lifetime has been around 10%."
      side: "right"
      align: "start"

  - element: "#EtfGrowthStdDev"
    popover:
      description: "<b>This is the expected standard deviation of the annual growth rate of your ETFs.</b><p/>For reference, the average volatility of the S&P500 over its lifetime (including bull markets and crashes) has been around 15%."
      side: "right"
      align: "start"

  - element: "#TrustGrowthRate"
    popover:
      description: "<b>This is the expected average annual growth rate of your investment trusts or shares, not adjusted for inflation.</b><p/>Keep in mind that investment trusts or shares tend to have higher fees, so take that into account when calculating this number."
      side: "right"
      align: "start"

  - element: "#TrustGrowthStdDev"
    popover:
      description: "<b>This is the expected standard deviation of the annual growth rate of your investment trusts or shares.</b><p/>For reference, the average volatility of the S&P500 over its lifetime (including bull markets and crashes) has been around 15%."
      side: "right"
      align: "start"

  - element: "#Inflation"
    popover:
      description: "<b>This is the expected average annual inflation rate.</b><p/>Central banks aim for an inflation rate of around 2%. However, deviations due to shocks (e.g., pandemics, wars, etc) can cause deviations that are skewed towards higher numbers. For example, in 2022 inflation was 7.8%, the highest since 1984. In contrast, by October 2024 it had decreased to 0.7%."
      side: "right"
      align: "start"

  - element: "#personalCircumstances"
    popover:
      description: "<b>Here you describe your personal circumstances.</b><p/>They may affect your income tax bands and tax credits, and would be difficult to capture as events."
      side: "right"
      align: "start"

  - element: "#MarriageYear"
    popover:
      description: "<b>Enter the year that you got married or entered into a civil partnership, or that you plan to.</b><p/>Your income tax band limits change if you are married or in a civil partnership. You can enter any year in the past if you were already married or in partnership, or a year in the future if you plan to get married or enter into a civil partnership then."
      side: "right"
      align: "start"

  - element: "#OldestChildBorn"
    popover:
      description: "<b>Enter the year that your oldest child was born or is expected or speculated to be born.</b><p/>Your income tax band limits are increased if you have dependent children, starting when your first child is born."
      side: "right"
      align: "start"

  - element: "#YoungestChildBorn"
    popover:
      description: "<b>Enter the year that your youngest child was born or is expected or speculated to be born.</b><p/>The increased income tax band limits for dependent children go on until your youngest child is over 18."
      side: "right"
      align: "start"

  - element: "#PersonalTaxCredit"
    popover:
      description: "<b>Enter the amount of personal tax credit you are entitled to according to your personal circumstances (widow, carer, etc).</b><p/>This is the amount of tax credit you get for yourself, before factoring in any dependent children (refer to [this revenue page](https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/tax-relief-charts/index.aspx))."
      side: "right"
      align: "start"

  - element: "#StatePensionWeekly"
    popover:
      description: "<b>Enter your expected weekly state pension amount.</b><p/>Given that different ways to calculate your state pension, refer to [this page](https://www.gov.ie/en/publication/b6193-how-to-calculate-your-state-pension-contributory-rate/) to find how to calculate yours."
      side: "right"
      align: "start"

  - element: "#drawdownPriorities"
    popover:
      description: "<b>Here you can set the priorities for the drawdown of your assets.</b><p/>You can drag and drop the items to change their order of priority. The top item will be the highest priority, meaning that it will be used first to cover your expenses when needed (for example in retirement)."
      side: "right"
      align: "start"

  - element: "#runSimulation"
    popover:
      description: "<b>Once you have entered all the data, click here to run the simulation.</b>"
      side: "bottom"
      align: "start"
  
  - element: "#cashflowGraph"
    popover:
      description: "<b>This graph shows your projected cashflow over time.</b>"
      side: "top"
      align: "center"
  
  - element: "#assetsGraph"
    popover:
      description: "<b>This graph shows your projected assets over time.</b>"
      side: "top"
      align: "center"
